version: '3.8'

services:
  # Serviço do Banco de Dados
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - ./.env # Aponta para o arquivo que conterá nossas senhas
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Serviço da nossa API em Spring Boot
  api:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - ./.env # Aponta para o mesmo arquivo de senhas

volumes:
  postgres_data:
