version: '3.8'

services:
  # Serviço do Banco de Dados
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: pet_connect
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Serviço da nossa API em Spring Boot
  api:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pet_connect
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  postgres_data: